services:
  signalcraft-rocky:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signalcraft-rocky

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - UDEV=1
      - TZ=America/New_York
      - DISPLAY=:99

    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb

    # keep Rocky home separate from Ubuntu's to avoid dotfile clashes
    volumes:
      - ${HOME}/signalcraft/rocky_gnuradio_docker/rocky/home/guser:/home/guser
      - ${HOME}/signalcraft/rocky_gnuradio_docker/rocky/app:/app

    # different ports from Ubuntu so both can run side-by-side
    ports:
      - "8091:8082"   # noVNC (internal 8082 now)
      - "5901:5900"   # native VNC
      

    shm_size: "2g"
    stdin_open: true
    tty: true
    restart: unless-stopped
