services:
  gnuradio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signalcraft-ubuntu

    # GPU (compatible with your Compose): 
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - UDEV=1
      - TZ=America/New_York
      - DISPLAY=:99

    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - ${HOME}/signalcraft/gnuradio_docker/home/guser:/home/guser
      - ${HOME}/signalcraft/gnuradio_docker/gnuradio:/app

    ports:
      - "8090:8080"    # noVNC
      - "5900:5900"    # native VNC (optional but handy)

    shm_size: "2g"
    stdin_open: true
    tty: true
    restart: unless-stopped

    # DEBUG: uncomment to pause the container so you can exec a shell
    # command: ["bash","-lc","sleep infinity"]
